import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

export const ACTIVITY_START = "<!-- AUTO:ACTIVITY:START -->";
export const ACTIVITY_END = "<!-- AUTO:ACTIVITY:END -->";

function escapeCell(value) {
  return String(value).replaceAll("|", "\\|").replaceAll("\n", " ");
}

function badgeSegment(value) {
  return encodeURIComponent(String(value).replaceAll("-", "--").replaceAll("_", "__").replaceAll(" ", "_"));
}

function renderLinks(links) {
  return links.map((link) => {
    const logo = link.logo ? `&logo=${encodeURIComponent(link.logo)}&logoColor=white` : "";
    const image = `https://img.shields.io/badge/${badgeSegment(link.label)}-${badgeSegment(link.value)}-${link.color}?style=for-the-badge${logo}`;
    return `  <a href="${link.url}"><img alt="${link.label}" src="${image}"></a>`;
  }).join("\n");
}

function renderFocus(focus) {
  return [
    "| Area | What I am exploring |",
    "| --- | --- |",
    ...focus.map((item) => `| **${escapeCell(item.name)}** | ${escapeCell(item.description)} |`)
  ].join("\n");
}

function renderProjects(projects) {
  return [
    "| Project | Focus | Why it matters |",
    "| --- | --- | --- |",
    ...projects.map((project) => {
      const homepage = project.homepage ? ` [Live](${project.homepage})` : "";
      return `| [**${escapeCell(project.name)}**](${project.url}) | ${escapeCell(project.focus)} | ${escapeCell(project.summary)}${homepage} |`;
    })
  ].join("\n");
}

function extractActivity(readme) {
  const startIndex = readme.indexOf(ACTIVITY_START);
  const endIndex = readme.indexOf(ACTIVITY_END);
  if (startIndex === -1 || endIndex === -1 || endIndex <= startIndex) return null;
  return readme.slice(startIndex + ACTIVITY_START.length, endIndex).trim();
}

async function readExistingActivity(readmePath) {
  try {
    const existing = await readFile(readmePath, "utf8");
    return extractActivity(existing);
  } catch (error) {
    if (error.code === "ENOENT") return null;
    throw error;
  }
}

function typingSvgUrl(config) {
  const lines = [config.profile.headline, config.profile.status, config.research.direction]
    .map((line) => encodeURIComponent(line))
    .join(";");
  return `https://readme-typing-svg.demolab.com?font=Fira+Code&pause=1000&color=39FF14&background=00000000&center=true&vCenter=true&width=560&height=45&lines=${lines}`;
}

function statsUrls(username) {
  return {
    // These three are generated by .github/workflows/cards.yml (default GITHUB_TOKEN, no PAT needed)
    // and committed as real files, so they never render blank the way the live vercel endpoints do.
    stats: "./profile/stats.svg",
    langs: "./profile/top-langs.svg",
    trophy: "./profile/trophy.svg",
    // streak-stats.herokuapp.com is dead (Heroku shut down free apps); the maintained domain is demolab.com.
    streak: `https://streak-stats.demolab.com/?user=${username}&theme=github-dark&background=0D1117&ring=39FF14&fire=39FF14&currStreakLabel=39FF14&hide_border=true`,
    visitors: `https://komarev.com/ghpvc/?username=${username}&label=Profile%20Views&color=39FF14&style=for-the-badge`,
    snakeDark: `https://raw.githubusercontent.com/${username}/${username}/output/github-contribution-grid-snake-dark.svg`,
    snakeLight: `https://raw.githubusercontent.com/${username}/${username}/output/github-contribution-grid-snake.svg`
  };
}

function waveCapsule({ height = 120, color = "0D1117" }) {
  return `https://capsule-render.vercel.app/api?type=waving&color=${color}&height=${height}&section=footer&animation=fadeIn`;
}

function scanlineBanner() {
  return "./assets/hero/cyber-scanline.svg";
}

export async function generateProfileReadme({ config, manifest, readmePath }) {
  const existingActivity = await readExistingActivity(readmePath);
  const activity = existingActivity || "_Recent public activity will appear here after the workflow runs._";
  const activitySection = config.activity.enabled
    ? `\n## Recent Activity\n\n${ACTIVITY_START}\n${activity}\n${ACTIVITY_END}\n`
    : "";
  const techStack = config.techStack.map((item) => `\`${item}\``).join(" · ");
  const about = config.profile.about.join("\n\n");
  const username = config.profile.username;
  const stats = statsUrls(username);
  const skillIcons = `https://skillicons.dev/icons?i=${config.techStack
    .map((item) => item.toLowerCase().replace(/[^a-z0-9+]/g, ""))
    .filter(Boolean)
    .join(",")}&theme=dark`;

  const readme = `<!-- Generated by GitHub Profile Agent Console. Edit profile.config.json, then run npm run generate. -->
<p align="center">
  <picture>
    <source media="(max-width: 760px) and (prefers-color-scheme: dark)" srcset="./assets/hero/${manifest.assets.mobileDark}">
    <source media="(max-width: 760px)" srcset="./assets/hero/${manifest.assets.mobileLight}">
    <source media="(prefers-color-scheme: dark)" srcset="./assets/hero/${manifest.assets.desktopDark}">
    <source media="(prefers-color-scheme: light)" srcset="./assets/hero/${manifest.assets.desktopLight}">
    <img src="./assets/hero/${manifest.assets.desktopDark}" alt="${config.profile.name} - ${config.profile.headline}" width="100%">
  </picture>
</p>

<p align="center">
  <img src="${scanlineBanner()}" width="100%" alt="Cyber scanline divider">
</p>

<p align="center">
  <img src="${typingSvgUrl(config)}" alt="Typing SVG">
</p>

<p align="center">
${renderLinks(config.links)}
  <img alt="Profile Views" src="${stats.visitors}">
  <img alt="Status" src="https://img.shields.io/badge/status-online-39FF14?style=for-the-badge&logo=statuspage&logoColor=black">
</p>

## About Me

${about}

## Current Focus

${renderFocus(config.focus)}

## Featured Work

${renderProjects(config.projects)}

## Research Direction

${config.research.narrative}

## Tech Stack

<p align="center">
  <img src="${skillIcons}" alt="Tech stack icons">
</p>

${techStack}

## GitHub Stats

<!-- These three SVGs are generated by .github/workflows/cards.yml — run it once after your first push. -->
<p align="center">
  <img src="${stats.stats}" alt="GitHub stats" height="165">
  <img src="${stats.langs}" alt="Top languages" height="165">
</p>

<p align="center">
  <img src="${stats.streak}" alt="GitHub streak" height="165">
</p>

<p align="center">
  <img src="${stats.trophy}" alt="GitHub trophies" width="100%">
</p>

## Contribution Snake

<p align="center">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="${stats.snakeDark}">
    <source media="(prefers-color-scheme: light)" srcset="${stats.snakeLight}">
    <img alt="Contribution snake animation" src="${stats.snakeDark}">
  </picture>
</p>
${activitySection}
---

<p align="center">
  <img src="${waveCapsule({ color: "0B1220", height: 100 })}" width="100%" alt="Footer wave">
</p>

<p align="center">
  ${config.footer}
</p>
`;

  await writeFile(resolve(readmePath), readme);
  return readme;
}
