name: Generate profile metrics

on:
  schedule:
    - cron: "30 2 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: ${{ github.repository_owner }}
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Jakarta
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_details: bytes-size
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
